// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKzK9Zb6_VVvkFxr-x0iGNGcgA5ucnvJE',
    appId: '1:540798100677:web:90a377aad88e9d738bbcac',
    messagingSenderId: '540798100677',
    projectId: 'free-code-camp-notes-app',
    authDomain: 'free-code-camp-notes-app.firebaseapp.com',
    storageBucket: 'free-code-camp-notes-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8peVPssbfeY-nBQ-bP6ufDHpfgWO5WDQ',
    appId: '1:540798100677:android:8d9f8152feec67b38bbcac',
    messagingSenderId: '540798100677',
    projectId: 'free-code-camp-notes-app',
    storageBucket: 'free-code-camp-notes-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0VvzPDYdP-6V6dWkvjKZ0WGbQzVK0uT8',
    appId: '1:540798100677:ios:bdaebfb834af79618bbcac',
    messagingSenderId: '540798100677',
    projectId: 'free-code-camp-notes-app',
    storageBucket: 'free-code-camp-notes-app.appspot.com',
    iosClientId: '540798100677-l310hh99k1c4vsd8hobsmi6iafchi02d.apps.googleusercontent.com',
    iosBundleId: 'com.example.catalogAppTut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0VvzPDYdP-6V6dWkvjKZ0WGbQzVK0uT8',
    appId: '1:540798100677:ios:bdaebfb834af79618bbcac',
    messagingSenderId: '540798100677',
    projectId: 'free-code-camp-notes-app',
    storageBucket: 'free-code-camp-notes-app.appspot.com',
    iosClientId: '540798100677-l310hh99k1c4vsd8hobsmi6iafchi02d.apps.googleusercontent.com',
    iosBundleId: 'com.example.catalogAppTut',
  );
}
